/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx,html}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface": "#0b1c30",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "error": "#ba1a1a",
        "warning-amber": "#F59E0B",
        "on-tertiary-container": "#8f92ff",
        "surface": "#f8f9ff",
        "surface-tint": "#3d57ba",
        "on-secondary-fixed-variant": "#005236",
        "surface-container-lowest": "#ffffff",
        "secondary": "#006c49",
        "surface-container": "#e6eeff",
        "success-emerald": "#6cf8bb",
        "surface-dim": "#cbdbf6",
        "on-error": "#ffffff",
        "primary-container": "#00288e",
        "on-primary-fixed": "#001453",
        "on-secondary-fixed": "#002113",
        "surface-container-high": "#dde9ff",
        "error-ruby": "#E11D48",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "on-background": "#0b1c30",
        "on-secondary-container": "#0c714d",
        "on-primary-fixed-variant": "#213da0",
        "surface-container-low": "#eff4ff",
        "outline-variant": "#c5c5d4",
        "on-tertiary-fixed": "#07006c",
        "surface-bright": "#f8f9ff",
        "primary-fixed-dim": "#b8c4ff",
        "surface-container-highest": "#d3e3ff",
        "secondary-fixed": "#9df4c8",
        "background": "#f8f9ff",
        "inverse-surface": "#213146",
        "secondary-fixed-dim": "#81d8ad",
        "outline": "#757684",
        "inverse-on-surface": "#ebf1ff",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#c0c1ff",
        "tertiary": "#080077",
        "tertiary-fixed": "#e1e0ff",
        "inverse-primary": "#b8c4ff",
        "secondary-container": "#9af2c5",
        "surface-variant": "#d3e3ff",
        "primary-fixed": "#dde1ff",
        "on-surface-variant": "#444652",
        "on-tertiary-fixed-variant": "#2f2dbe",
        "primary": "#00175c",
        "tertiary-container": "#170bae",
        "on-primary-container": "#7e97fe",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
      spacing: {
        "margin-desktop": "32px",
        "gutter": "16px",
        "margin-mobile": "16px",
        "xs": "4px",
        "base": "4px",
        "md": "16px",
        "lg": "24px",
        "sm": "8px",
        "xl": "32px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Space Grotesk", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-md": ["Space Grotesk", "sans-serif"],
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "display-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
